server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xdoqlgqbpfyhjx:508625b5a324b1596ec46bcbaffd0fc457206bcd09c60709d920fe36a3f231c6@ec2-52-206-193-199.compute-1.amazonaws.com:5432/d1itfq6pcj9vm9
    username: xdoqlgqbpfyhjx
    password: 508625b5a324b1596ec46bcbaffd0fc457206bcd09c60709d920fe36a3f231c6
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / BackEnd